from pathlib import Path

# Get all health blog files (excluding index.html)
health_dir = Path('dog-blog/health')
health_files = sorted([f.name for f in health_dir.glob('*.html') if f.name != 'index.html'])

# Build sitemap content
xml_lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
]

# Add all URLs
all_urls = [
    'about.html',
    'bird/index.html',
    'bird-blog/index.html',
    'calculators.html',
    'cat/cat-age-calculator.html',
    'cat/cat-food-calculator.html',
    'cat/cat-pregnancy-calculator.html',
    'cat/cat-water-intake-calculator.html',
    'cat/index.html',
    'cat-blog/cat-pregnancy-length-explained.html',
    'cat-blog/how-much-food-should-i-feed-my-cat.html',
    'cat-blog/how-much-water-should-a-cat-drink.html',
    'cat-blog/how-to-calculate-cat-age.html',
    'contact.html',
    'dog/calculators.html',
    'dog/dog-age-calculator.html',
    'dog/dog-bmi-calculator.html',
    'dog/dog-body-condition-score-calculator.html',
    'dog/dog-calorie-calculator.html',
    'dog/dog-daily-protein-calculator.html',
    'dog/dog-due-date-calculator.html',
    'dog/dog-exercise-calculator.html',
    'dog/dog-feeding-schedule-calculator.html',
    'dog/dog-food-calculator.html',
    'dog/dog-food-cost-calculator.html',
    'dog/dog-gestation-period-calculator.html',
    'dog/dog-heat-cycle-calculator.html',
    'dog/dog-ideal-weight-calculator.html',
    'dog/dog-life-expectancy-calculator.html',
    'dog/dog-pregnancy-calculator.html',
    'dog/dog-pregnancy-timeline.html',
    'dog/dog-pregnancy-week-calculator.html',
    'dog/dog-quality-of-life-calculator.html',
    'dog/dog-raw-food-calculator.html',
    'dog/dog-rer-calculator.html',
    'dog/dog-size-calculator.html',
    'dog/dog-treat-calorie-calculator.html',
    'dog/dog-walking-calorie-calculator.html',
    'dog/dog-water-intake-calculator.html',
    'dog/dog-weight-gain-calculator.html',
    'dog/dog-weight-loss-calculator.html',
    'dog/dog-years-to-human-years-chart.html',
    'dog/index.html',
    'dog/puppy-growth-stages-month-by-month.html',
    'dog/puppy-vaccination-calculator.html',
    'dog/puppy-weight-calculator.html',
    'dog/senior-dog-age-calculator.html',
    'dog-blog/behavior/index.html',
    'dog-blog/breeds/index.html',
    'dog-blog/exercise/index.html',
    'dog-blog/health/index.html',
]

# Add health files
for filename in health_files:
    all_urls.append(f'dog-blog/health/{filename}')

# Continue with other URLs
other_urls = [
    'dog-blog/how-much-food-should-i-feed-my-dog.html',
    'dog-blog/how-much-water-should-a-dog-drink.html',
    'dog-blog/how-to-calculate-dog-age.html',
    'dog-blog/index.html',
    'dog-blog/nutrition/best-dog-food-brands.html',
    'dog-blog/nutrition/best-dog-food-for-active-dogs.html',
    'dog-blog/nutrition/best-dog-food-for-allergies.html',
    'dog-blog/nutrition/best-dog-food-for-diabetic-dogs.html',
    'dog-blog/nutrition/best-dog-food-for-digestive-health.html',
    'dog-blog/nutrition/best-dog-food-for-itchy-skin.html',
    'dog-blog/nutrition/best-dog-food-for-joint-health.html',
    'dog-blog/nutrition/best-dog-food-for-kidney-disease.html',
    'dog-blog/nutrition/best-dog-food-for-large-breeds.html',
    'dog-blog/nutrition/best-dog-food-for-older-dogs.html',
    'dog-blog/nutrition/best-dog-food-for-puppies.html',
    'dog-blog/nutrition/best-dog-food-for-senior-dogs.html',
    'dog-blog/nutrition/best-dog-food-for-sensitive-stomachs.html',
    'dog-blog/nutrition/best-dog-food-for-skin-allergies.html',
    'dog-blog/nutrition/best-dog-food-for-small-breeds.html',
    'dog-blog/nutrition/best-dog-food-for-weight-gain.html',
    'dog-blog/nutrition/best-dog-food-for-weight-loss.html',
    'dog-blog/nutrition/best-dog-food-for-weight-management.html',
    'dog-blog/nutrition/best-dry-dog-food.html',
    'dog-blog/nutrition/best-food-for-puppies.html',
    'dog-blog/nutrition/best-food-for-senior-dogs.html',
    'dog-blog/nutrition/best-grain-free-dog-food.html',
    'dog-blog/nutrition/best-high-protein-dog-foods.html',
    'dog-blog/nutrition/best-wet-dog-food.html',
    'dog-blog/nutrition/can-dogs-eat-apples.html',
    'dog-blog/nutrition/can-dogs-eat-avocado.html',
    'dog-blog/nutrition/can-dogs-eat-bananas.html',
    'dog-blog/nutrition/can-dogs-eat-blackberries.html',
    'dog-blog/nutrition/can-dogs-eat-blueberries.html',
    'dog-blog/nutrition/can-dogs-eat-bread.html',
    'dog-blog/nutrition/can-dogs-eat-broccoli.html',
    'dog-blog/nutrition/can-dogs-eat-carrots.html',
    'dog-blog/nutrition/can-dogs-eat-cheese.html',
    'dog-blog/nutrition/can-dogs-eat-cherries.html',
    'dog-blog/nutrition/can-dogs-eat-chicken.html',
    'dog-blog/nutrition/can-dogs-eat-coconut.html',
    'dog-blog/nutrition/can-dogs-eat-corn.html',
    'dog-blog/nutrition/can-dogs-eat-cucumbers.html',
    'dog-blog/nutrition/can-dogs-eat-eggs.html',
    'dog-blog/nutrition/can-dogs-eat-grapes.html',
    'dog-blog/nutrition/can-dogs-eat-green-beans.html',
    'dog-blog/nutrition/can-dogs-eat-kiwi.html',
    'dog-blog/nutrition/can-dogs-eat-mango.html',
    'dog-blog/nutrition/can-dogs-eat-oatmeal.html',
    'dog-blog/nutrition/can-dogs-eat-oranges.html',
    'dog-blog/nutrition/can-dogs-eat-peaches.html',
    'dog-blog/nutrition/can-dogs-eat-peanut-butter.html',
    'dog-blog/nutrition/can-dogs-eat-pears.html',
    'dog-blog/nutrition/can-dogs-eat-pineapple.html',
    'dog-blog/nutrition/can-dogs-eat-popcorn.html',
    'dog-blog/nutrition/can-dogs-eat-pork.html',
    'dog-blog/nutrition/can-dogs-eat-potatoes.html',
    'dog-blog/nutrition/can-dogs-eat-pumpkin.html',
    'dog-blog/nutrition/can-dogs-eat-raspberries.html',
    'dog-blog/nutrition/can-dogs-eat-rice.html',
    'dog-blog/nutrition/can-dogs-eat-salmon.html',
    'dog-blog/nutrition/can-dogs-eat-spinach.html',
    'dog-blog/nutrition/can-dogs-eat-strawberries.html',
    'dog-blog/nutrition/can-dogs-eat-sweet-potatoes.html',
    'dog-blog/nutrition/can-dogs-eat-tomatoes.html',
    'dog-blog/nutrition/can-dogs-eat-tuna.html',
    'dog-blog/nutrition/can-dogs-eat-turkey.html',
    'dog-blog/nutrition/can-dogs-eat-watermelon.html',
    'dog-blog/nutrition/can-dogs-eat-yogurt.html',
    'dog-blog/nutrition/diabetes-diet-for-dogs.html',
    'dog-blog/nutrition/dog-feeding-chart-by-age.html',
    'dog-blog/nutrition/dog-feeding-chart-by-weight.html',
    'dog-blog/nutrition/dog-feeding-schedule-by-age.html',
    'dog-blog/nutrition/dog-weight-gain-diet-guide.html',
    'dog-blog/nutrition/dog-weight-loss-diet-guide.html',
    'dog-blog/nutrition/foods-dogs-should-never-eat.html',
    'dog-blog/nutrition/grain-free-diet-for-dogs.html',
    'dog-blog/nutrition/high-fiber-diet-for-dogs.html',
    'dog-blog/nutrition/homemade-dog-food-guide.html',
    'dog-blog/nutrition/how-long-can-a-dog-go-without-food.html',
    'dog-blog/nutrition/how-many-calories-does-my-dog-need.html',
    'dog-blog/nutrition/how-many-times-should-a-dog-eat-per-day.html',
    'dog-blog/nutrition/how-much-dry-food-should-a-dog-eat.html',
    'dog-blog/nutrition/how-much-food-should-i-feed-my-dog.html',
    'dog-blog/nutrition/how-much-should-a-puppy-eat.html',
    'dog-blog/nutrition/how-much-should-a-senior-dog-eat.html',
    'dog-blog/nutrition/how-much-water-should-a-dog-drink.html',
    'dog-blog/nutrition/how-much-wet-food-should-a-dog-eat.html',
    'dog-blog/nutrition/how-often-should-puppies-eat.html',
    'dog-blog/nutrition/how-to-measure-dog-food-correctly.html',
    'dog-blog/nutrition/hypoallergenic-dog-diet.html',
    'dog-blog/nutrition/index.html',
    'dog-blog/nutrition/kidney-disease-diet-for-dogs.html',
    'dog-blog/nutrition/low-fat-diet-for-dogs.html',
    'dog-blog/nutrition/protein-requirements-for-dogs.html',
    'dog-blog/nutrition/puppy-nutrition-guide.html',
    'dog-blog/nutrition/raw-diet-for-dogs.html',
    'dog-blog/nutrition/senior-dog-nutrition-guide.html',
    'dog-blog/nutrition/should-dogs-eat-once-or-twice-a-day.html',
    'dog-blog/nutrition/wet-food-vs-dry-food-for-dogs.html',
    'dog-blog/nutrition/what-time-should-i-feed-my-dog.html',
    'dog-blog/nutrition/when-should-dogs-eat-before-bed.html',
    'dog-blog/nutrition/when-should-puppies-switch-to-adult-food.html',
    'dog-blog/nutrition/why-is-my-dog-always-hungry.html',
    'dog-blog/nutrition/why-is-my-dog-eating-too-fast.html',
    'dog-blog/nutrition/why-is-my-dog-not-eating.html',
    'dog-blog/pregnancy/index.html',
    'dog-blog/puppy/index.html',
    'dog-blog/senior/index.html',
    'dog-blog/signs-your-dog-is-overweight.html',
    'fish/index.html',
    'google02c769f5b0af9467.html',
    'guides.html',
    'guinea-pig/index.html',
    'hamster/index.html',
    'horse/index.html',
    'index.html',
    'privacy-policy.html',
    'rabbit/index.html',
    'reptile/index.html',
    'terms.html',
    'turtle/index.html',
]

all_urls.extend(other_urls)

# Add URL entries
for url_path in all_urls:
    xml_lines.append('  <url>')
    xml_lines.append(f'    <loc>https://mmm071026246-lgtm.github.io/{url_path}</loc>')
    xml_lines.append('  </url>')

xml_lines.append('</urlset>')

# Write sitemap
with open('sitemap.xml', 'w', encoding='utf-8') as f:
    f.write('\n'.join(xml_lines))

print(f'✓ Sitemap updated with {len(health_files)} health articles')
print(f'✓ Total URLs: {len(all_urls)}')
